## Case 1: without solar and gas costs, only CO2 store cost

In [1]:
import pypsa
import numpy as np

# Create network
n = pypsa.Network()
n.set_snapshots(range(7))  # Adjust as needed

# --- Buses ---
n.add(
    "Bus",
    "elec",
    carrier="AC",
)

n.add(
    "Generator",
    "solar_gen",
    bus="elec",
    carrier="solar",
    p_nom_extendable=True,
    capital_cost=0,
    p_max_pu=[1,1,1,1,0,0,0]
)


n.add(
    "Bus",
    "co2",
    carrier="CO2",
)


n.add(
    "Bus",
    "gas",
    carrier="gas",
)

n.add(
    "Generator",
    "gas_gen",
    bus="gas",
    carrier="gas",
    p_nom_extendable=True,
    capital_cost=0
)

n.add(
    "Load",
    "load",
    bus="elec",
    p_set=1,
)

n.add(
        "Link",
        "gas",
        bus0='gas',
        bus1='elec',
        bus2='co2',
        carrier="gas",
        p_nom_extendable=True,
        capital_cost=0,  # EUR/MW_H2/a
        lifetime=20,
        efficiency=1,
        efficiency2=1,
)


#----stores----#

n.add(
        "Store",
        "co2_store",
        bus='co2',
        carrier="co2",
        e_nom_extendable=True,
        capital_cost=100,  # EUR/MW_H2/a
        lifetime=20,
        e_nom_max=8, ## or 8
    )

# --- Solve ---
n.optimize(solver_name="gurobi")  # Uncomment to solve
n.statistics()  # View results

WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['solar_gen', 'gas_gen'], dtype='object', name='Generator')
WARNING:pypsa.consistency:The following links have carriers which are not defined:
Index(['gas'], dtype='object', name='Link')
WARNING:pypsa.consistency:The following stores have carriers which are not defined:
Index(['co2_store'], dtype='object', name='Store')
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['elec', 'co2', 'gas'], dtype='object', name='Bus')
INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.io: Writing time: 0.03s

Set parameter Username

INFO:gurobipy:Set parameter Username

Academic license - for non-commercial use only - expires 2027-02-07

INFO:gurobipy:Academic license - for non-commercial use only - expires 2027-02-07

Read LP format model from file /private/var/folders/wj/l6v21q_91nb2btzb1f5q6vw8zw_2j1/T/linopy-problem-yl45e9fr.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/wj/l6v21q_91nb2btzb1f5q6vw8zw_2j1/T/linopy-problem-yl45e9fr.lp

Reading time = 0.00 seconds

INFO:gurobipy:Reading time = 0.00 seconds

obj: 89 rows, 39 columns, 148 nonzeros

INFO:gurobipy:obj: 89 rows, 39 columns, 148 nonzeros

Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (mac64[arm] - Darwin 25.4.0 25E246)

INFO:gurobipy:Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (mac64[arm] - Darwin 25.4.0 25E246)

INFO:gurobipy:

CPU model: Apple M1 Pro

INFO:gurobipy:CPU model: Apple M1 Pro

Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 89 rows, 39 columns and 148 nonzeros

INFO:gurobipy:Optimize a model with 89 rows, 39 columns and 148 nonzeros

Model fingerprint: 0x21749d6c

INFO:gurobipy:Model fingerprint: 0x21749d6c

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [1e+00, 1e+00]

INFO:gurobipy:  Matrix range     [1e+00, 1e+00]

  Objective range  [1e+02, 1e+02]

INFO:gurobipy:  Objective range  [1e+02, 1e+02]

  Bounds range     [0e+00, 0e+00]

INFO:gurobipy:  Bounds range     [0e+00, 0e+00]

  RHS range        [1e+00, 8e+00]

INFO:gurobipy:  RHS range        [1e+00, 8e+00]

Presolve removed 89 rows and 39 columns

INFO:gurobipy:Presolve removed 89 rows and 39 columns

Presolve time: 0.01s

INFO:gurobipy:Presolve time: 0.01s

Presolve: All rows and columns removed

INFO:gurobipy:Presolve: All rows and columns removed

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

       0    3.0000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:       0    3.0000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 0 iterations and 0.01 seconds (0.00 work units)

INFO:gurobipy:Solved in 0 iterations and 0.01 seconds (0.00 work units)

Optimal objective  3.000000000e+02

INFO:gurobipy:Optimal objective  3.000000000e+02
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 39 primals, 89 duals
Objective: 3.00e+02
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper, Link-ext-p-lower, Link-ext-p-upper, Store-ext-e-lower, Store-ext-e-upper, Store-energy_balance were not assigned to the network.

                 Optimal Capacity  Installed Capacity  Supply  Withdrawal  \
Generator gas                 1.0                 0.0     3.0         0.0
          solar               1.0                 0.0     4.0         0.0
Link      gas                 1.0                 0.0     0.0         3.0
Load      -                   0.0                 0.0     0.0         7.0
Store     co2                 3.0                 0.0     0.0         3.0

                 Energy Balance Transmission  Capacity Factor  Curtailment  \
Generator gas               3.0          0.0         0.428570          4.0
          solar             4.0          0.0         0.571430          0.0
Link      gas              -3.0          0.0         0.428570          0.0
Load      -                -7.0          0.0              NaN          0.0
Store     co2              -3.0          0.0         0.285713          0.0

                 Capital Expenditure  Operational Expenditure  Revenue  \
Generator gas                    0.0                      0.0      0.0
          solar                  0.0                      0.0      0.0
Link      gas                    0.0                      0.0      0.0
Load      -                      0.0                      0.0   -300.0
Store     co2                  300.0                      0.0    300.0

                 Market Value
Generator gas             NaN
          solar           NaN
Link      gas             0.0
Load      -               NaN
Store     co2             NaN

In [26]:
n.buses_t.marginal_price

Bus        elec    co2  gas
snapshot
0           0.0    0.0  0.0
1           0.0 -100.0  0.0
2           0.0 -100.0  0.0
3           0.0 -100.0  0.0
4         100.0 -100.0  0.0
5         100.0 -100.0  0.0
6         100.0 -100.0  0.0

In [27]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0                1.0      0.0
1                1.0      0.0
2                1.0      0.0
3                1.0      0.0
4                0.0      1.0
5                0.0      1.0
6                0.0      1.0

### if e_nom_max=8 (non-binding)

In [33]:
n.buses_t.marginal_price

Bus        elec    co2  gas
snapshot
0           0.0    0.0  0.0
1           0.0 -100.0  0.0
2           0.0 -100.0  0.0
3           0.0 -100.0  0.0
4         100.0 -100.0  0.0
5         100.0 -100.0  0.0
6         100.0 -100.0  0.0

In [34]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0                1.0      0.0
1                1.0      0.0
2                1.0      0.0
3                1.0      0.0
4                0.0      1.0
5                0.0      1.0
6                0.0      1.0

## Case 2: with solar and gas costs (no CO2 store cost)
### gas and solar control co2 price

In [22]:
import pypsa
import numpy as np

# Create network
n = pypsa.Network()
n.set_snapshots(range(7))  # Adjust as needed

# --- Buses ---
n.add(
    "Bus",
    "elec",
    carrier="AC",
)

n.add(
    "Generator",
    "solar_gen",
    bus="elec",
    carrier="solar",
    p_nom_extendable=True,
    capital_cost=200,
    p_max_pu=[1,1,1,1,0,0,0]
)


n.add(
    "Bus",
    "co2",
    carrier="CO2",
)


n.add(
    "Bus",
    "gas",
    carrier="gas",
)

n.add(
    "Generator",
    "gas_gen",
    bus="gas",
    carrier="gas",
    p_nom_extendable=True,
    capital_cost=100
)

n.add(
    "Load",
    "load",
    bus="elec",
    p_set=1,
)

n.add(
        "Link",
        "gas",
        bus0='gas',
        bus1='elec',
        bus2='co2',
        carrier="gas",
        p_nom_extendable=True,
        capital_cost=0,  # EUR/MW_H2/a
        lifetime=20,
        efficiency=1,
        efficiency2=1,
)


#----stores----#

n.add(
        "Store",
        "co2_store",
        bus='co2',
        carrier="co2",
        e_nom_extendable=True,
        capital_cost=0,  # EUR/MW_H2/a
        lifetime=20,
        e_nom_max=3, ## or 4
    )

# --- Solve ---
n.optimize(solver_name="gurobi")  # Uncomment to solve
n.statistics()  # View results

WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['elec', 'co2', 'gas'], dtype='object', name='Bus')
WARNING:pypsa.consistency:The following stores have carriers which are not defined:
Index(['co2_store'], dtype='object', name='Store')
WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['solar_gen', 'gas_gen'], dtype='object', name='Generator')
WARNING:pypsa.consistency:The following links have carriers which are not defined:
Index(['gas'], dtype='object', name='Link')
INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.io: Writing time: 0.07s

Set parameter TokenServer to value "sophia1.hpc.ait.dtu.dk"

INFO:gurobipy:Set parameter TokenServer to value "sophia1.hpc.ait.dtu.dk"

Read LP format model from file /tmp/linopy-problem-y88_ygbq.lp

INFO:gurobipy:Read LP format model from file /tmp/linopy-problem-y88_ygbq.lp

Reading time = 0.00 seconds

INFO:gurobipy:Reading time = 0.00 seconds

obj: 89 rows, 39 columns, 148 nonzeros

INFO:gurobipy:obj: 89 rows, 39 columns, 148 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (linux64 - "CentOS Linux 7 (Core)")

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (linux64 - "CentOS Linux 7 (Core)")

INFO:gurobipy:

CPU model: AMD EPYC 7351 16-Core Processor, instruction set [SSE2|AVX|AVX2]

INFO:gurobipy:CPU model: AMD EPYC 7351 16-Core Processor, instruction set [SSE2|AVX|AVX2]

Thread count: 32 physical cores, 32 logical processors, using up to 32 threads

INFO:gurobipy:Thread count: 32 physical cores, 32 logical processors, using up to 32 threads

INFO:gurobipy:

Optimize a model with 89 rows, 39 columns and 148 nonzeros

INFO:gurobipy:Optimize a model with 89 rows, 39 columns and 148 nonzeros

Model fingerprint: 0x184e9d78

INFO:gurobipy:Model fingerprint: 0x184e9d78

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [1e+00, 1e+00]

INFO:gurobipy:  Matrix range     [1e+00, 1e+00]

  Objective range  [1e+02, 2e+02]

INFO:gurobipy:  Objective range  [1e+02, 2e+02]

  Bounds range     [0e+00, 0e+00]

INFO:gurobipy:  Bounds range     [0e+00, 0e+00]

  RHS range        [1e+00, 4e+00]

INFO:gurobipy:  RHS range        [1e+00, 4e+00]

Presolve removed 84 rows and 34 columns

INFO:gurobipy:Presolve removed 84 rows and 34 columns

Presolve time: 0.01s

INFO:gurobipy:Presolve time: 0.01s

Presolved: 5 rows, 5 columns, 12 nonzeros

INFO:gurobipy:Presolved: 5 rows, 5 columns, 12 nonzeros

INFO:gurobipy:

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

       0    1.0000000e+02   3.000000e+00   0.000000e+00      0s

INFO:gurobipy:       0    1.0000000e+02   3.000000e+00   0.000000e+00      0s

       4    2.5000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:       4    2.5000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 4 iterations and 0.01 seconds (0.00 work units)

INFO:gurobipy:Solved in 4 iterations and 0.01 seconds (0.00 work units)

Optimal objective  2.500000000e+02

INFO:gurobipy:Optimal objective  2.500000000e+02
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 39 primals, 89 duals
Objective: 2.50e+02
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper, Link-ext-p-lower, Link-ext-p-upper, Store-ext-e-lower, Store-ext-e-upper, Store-energy_balance were not assigned to the network.

                 Optimal Capacity  Installed Capacity  Supply  Withdrawal  \
Generator gas                1.00                 0.0     4.0         0.0
          solar              0.75                 0.0     3.0         0.0
Link      gas                1.00                 0.0     8.0         4.0
Load      -                  0.00                 0.0     0.0         7.0
Store     co2                4.00                 0.0     0.0         4.0

                 Energy Balance  Transmission  Capacity Factor  Curtailment  \
Generator gas               4.0           0.0         0.571430          3.0
          solar             3.0           0.0         0.571427          0.0
Link      gas               4.0           0.0         0.571430          0.0
Load      -                -7.0           0.0              NaN          0.0
Store     co2              -4.0           0.0         0.410715          0.0

                 Capital Expenditure  Operational Expenditure  Revenue  \
Generator gas                  100.0                      0.0    100.0
          solar                150.0                      0.0    150.0
Link      gas                    0.0                      0.0      0.0
Load      -                      0.0                      0.0   -450.0
Store     co2                    0.0                      0.0    200.0

                 Market Value
Generator gas       24.999930
          solar     50.000163
Link      gas             NaN
Load      -               NaN
Store     co2             NaN

In [20]:
n.buses_t.marginal_price

Bus        elec    co2    gas
snapshot
0           0.0    0.0    0.0
1           0.0    0.0    0.0
2           0.0    0.0    0.0
3         200.0 -200.0    0.0
4         300.0 -200.0  100.0
5         200.0 -200.0    0.0
6         200.0 -200.0    0.0

In [21]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0                1.0      0.0
1                1.0      0.0
2                1.0      0.0
3                1.0      0.0
4                0.0      1.0
5                0.0      1.0
6                0.0      1.0

## if e_nom_max= 4 (non-binding)

In [23]:
n.buses_t.marginal_price

Bus        elec   co2    gas
snapshot
0          50.0 -50.0    0.0
1          50.0 -50.0    0.0
2          50.0 -50.0    0.0
3          50.0 -50.0    0.0
4         150.0 -50.0  100.0
5          50.0 -50.0    0.0
6          50.0 -50.0    0.0

In [24]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0               0.75     0.25
1               0.75     0.25
2               0.75     0.25
3               0.75     0.25
4               0.00     1.00
5               0.00     1.00
6               0.00     1.00

In [43]:
import pypsa
import numpy as np

# Create network
n = pypsa.Network()
n.set_snapshots(range(7))  # Adjust as needed

# --- Buses ---
n.add(
    "Bus",
    "elec",
    carrier="AC",
)

n.add(
    "Generator",
    "solar_gen",
    bus="elec",
    carrier="solar",
    p_nom_extendable=True,
    capital_cost=200,
    p_max_pu=[1,1,1,1,0,0,0]
)


n.add(
    "Bus",
    "co2",
    carrier="CO2",
)


n.add(
    "Bus",
    "gas",
    carrier="gas",
)

n.add(
    "Generator",
    "gas_gen",
    bus="gas",
    carrier="gas",
    p_nom_extendable=True,
    capital_cost=100
)

n.add(
    "Load",
    "load",
    bus="elec",
    p_set=1,
)

n.add(
        "Link",
        "gas",
        bus0='gas',
        bus1='elec',
        bus2='co2',
        carrier="gas",
        p_nom_extendable=True,
        capital_cost=0,  # EUR/MW_H2/a
        lifetime=20,
        efficiency=1,
        efficiency2=1,
)


#----stores----#

n.add(
        "Store",
        "co2_store",
        bus='co2',
        carrier="co2",
        e_nom_extendable=True,
        capital_cost=20,  # EUR/MW_H2/a
        lifetime=20,
        e_nom_max=3, ## or 4
    )

# --- Solve ---
n.optimize(solver_name="gurobi")  # Uncomment to solve
n.statistics()  # View results

WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['elec', 'co2', 'gas'], dtype='object', name='Bus')
WARNING:pypsa.consistency:The following stores have carriers which are not defined:
Index(['co2_store'], dtype='object', name='Store')
WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['solar_gen', 'gas_gen'], dtype='object', name='Generator')
WARNING:pypsa.consistency:The following links have carriers which are not defined:
Index(['gas'], dtype='object', name='Link')
INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.io: Writing time: 0.07s

Set parameter TokenServer to value "sophia1.hpc.ait.dtu.dk"

INFO:gurobipy:Set parameter TokenServer to value "sophia1.hpc.ait.dtu.dk"

Read LP format model from file /tmp/linopy-problem-m0grs7y2.lp

INFO:gurobipy:Read LP format model from file /tmp/linopy-problem-m0grs7y2.lp

Reading time = 0.00 seconds

INFO:gurobipy:Reading time = 0.00 seconds

obj: 89 rows, 39 columns, 148 nonzeros

INFO:gurobipy:obj: 89 rows, 39 columns, 148 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (linux64 - "CentOS Linux 7 (Core)")

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (linux64 - "CentOS Linux 7 (Core)")

INFO:gurobipy:

CPU model: AMD EPYC 7351 16-Core Processor, instruction set [SSE2|AVX|AVX2]

INFO:gurobipy:CPU model: AMD EPYC 7351 16-Core Processor, instruction set [SSE2|AVX|AVX2]

Thread count: 32 physical cores, 32 logical processors, using up to 32 threads

INFO:gurobipy:Thread count: 32 physical cores, 32 logical processors, using up to 32 threads

INFO:gurobipy:

Optimize a model with 89 rows, 39 columns and 148 nonzeros

INFO:gurobipy:Optimize a model with 89 rows, 39 columns and 148 nonzeros

Model fingerprint: 0xdd0ea986

INFO:gurobipy:Model fingerprint: 0xdd0ea986

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [1e+00, 1e+00]

INFO:gurobipy:  Matrix range     [1e+00, 1e+00]

  Objective range  [2e+01, 2e+02]

INFO:gurobipy:  Objective range  [2e+01, 2e+02]

  Bounds range     [0e+00, 0e+00]

INFO:gurobipy:  Bounds range     [0e+00, 0e+00]

  RHS range        [1e+00, 3e+00]

INFO:gurobipy:  RHS range        [1e+00, 3e+00]

Presolve removed 89 rows and 39 columns

INFO:gurobipy:Presolve removed 89 rows and 39 columns

Presolve time: 0.01s

INFO:gurobipy:Presolve time: 0.01s

Presolve: All rows and columns removed

INFO:gurobipy:Presolve: All rows and columns removed

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

       0    3.6000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:       0    3.6000000e+02   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 0 iterations and 0.01 seconds (0.00 work units)

INFO:gurobipy:Solved in 0 iterations and 0.01 seconds (0.00 work units)

Optimal objective  3.600000000e+02

INFO:gurobipy:Optimal objective  3.600000000e+02
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 39 primals, 89 duals
Objective: 3.60e+02
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper, Link-ext-p-lower, Link-ext-p-upper, Store-ext-e-lower, Store-ext-e-upper, Store-energy_balance were not assigned to the network.

                 Optimal Capacity  Installed Capacity  Supply  Withdrawal  \
Generator gas                 1.0                 0.0     3.0         0.0
          solar               1.0                 0.0     4.0         0.0
Link      gas                 1.0                 0.0     6.0         3.0
Load      -                   0.0                 0.0     0.0         7.0
Store     co2                 3.0                 0.0     0.0         3.0

                 Energy Balance  Transmission  Capacity Factor  Curtailment  \
Generator gas               3.0           0.0         0.428570          4.0
          solar             4.0           0.0         0.571430          0.0
Link      gas               3.0           0.0         0.428570          0.0
Load      -                -7.0           0.0              NaN          0.0
Store     co2              -3.0           0.0         0.285713          0.0

                 Capital Expenditure  Operational Expenditure  Revenue  \
Generator gas                  100.0                      0.0    100.0
          solar                200.0                      0.0    200.0
Link      gas                    0.0                      0.0      0.0
Load      -                      0.0                      0.0   -900.0
Store     co2                   60.0                      0.0    600.0

                 Market Value
Generator gas       33.333434
          solar     49.999878
Link      gas             NaN
Load      -               NaN
Store     co2             NaN

In [44]:
n.buses_t.marginal_price

Bus        elec    co2    gas
snapshot
0         200.0 -200.0    0.0
1           0.0 -200.0    0.0
2           0.0 -200.0    0.0
3           0.0 -200.0    0.0
4         300.0 -200.0  100.0
5         200.0 -200.0    0.0
6         200.0 -200.0    0.0

In [45]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0                1.0      0.0
1                1.0      0.0
2                1.0      0.0
3                1.0      0.0
4                0.0      1.0
5                0.0      1.0
6                0.0      1.0

In [47]:
n.stores_t.e

Store     co2_store
snapshot
0               0.0
1               0.0
2               0.0
3               0.0
4               1.0
5               2.0
6               3.0

## if e_nom_max= 4 (non-binding)

In [39]:
n.buses_t.marginal_price

Bus        elec   co2    gas
snapshot
0          50.0 -50.0    0.0
1          50.0 -50.0    0.0
2          50.0 -50.0    0.0
3          50.0 -50.0    0.0
4         150.0 -50.0  100.0
5          50.0 -50.0    0.0
6          50.0 -50.0    0.0

In [40]:
n.generators_t.p

Generator  solar_gen  gas_gen
snapshot
0               0.75     0.25
1               0.75     0.25
2               0.75     0.25
3               0.75     0.25
4               0.00     1.00
5               0.00     1.00
6               0.00     1.00